# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cocoapodDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocoapodDemo
  pod ‘SpriteKit-Components’, '~> 1.0.2’
end
